name: build-test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["10", "12", "14", "16"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        shell: bash
        with:
          fetch-depth: 0
      - name: Setup node
        shell: bash
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          # cache: npm
      - run: npm i
        shell: bash
      - run: npm run prettier:diff
        shell: bash
      - run: npm run prettier:check
        shell: bash
      - run: npm run lint-staged
        shell: bash