name: build-test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: ["14", "15"]
        os: [windows-latest]
    defaults:
      run:
        shell: bash
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          # cache: npm
      - run: npm cache clean –force
      - run: npm i
      - run: npm run prettier -- --version
      - run: npm run prettier:diff
      - run: npm run prettier:check
      - run: npm run lint-staged