name: main-workflow

on:
  push:
    branches:
      - development
    paths-ignore:
      - "**.md"
      - "**.png"
      - "cspell.json"
      - ".vscode/"

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: ["10", "12", "14", "16"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: bash
    concurrency:
      group: ${{matrix.os}}-${{matrix.node}}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm i
      - run: npm run prettier:check
      - run: npm run lint-staged
      - run: npm run prettier:check
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: "14"
          cache: npm
      - run: npm i
      - run: npm run test
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: "14"
          cache: npm
      - run: npm i
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  sync-branch:
    needs: [deploy]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Merge development -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: development
          target_branch: main
          github_token: ${{ github.token }}